remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
lang: en-US
title: vaficionado.com
email:
description: where the cloud meets the vines
baseurl: /vaficionado # the optional subpath of your site, e.g. "/blog"
url: https://jonnyborbs.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
author:
  name: Jon
  twitter: jonnyborbs
  picture:  /assets/images/IMG_3198.jpg
twitter_username: jonnyborbs
github_username: jonnyborbs
logo: # path of site logo, e.g. "/vaficionado/assets/images/logo.png"
search: true # true, false (default)
search_full_content: true # true, false (default)
search_provider: # lunr (default), algolia
paginate: 5
paginate_path: /page:num/