remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
lang: en-US
title: vaficionado
description: where the cloud meets the vines
baseurl: # the optional subpath of your site, e.g. "/blog"
url: http://vaficionado.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
author:
  name: jon
  twitter: jonnyborbs
  picture:  /assets/images/IMG_3198.jpg
twitter_username: jonnyborbs
github_username: jonnyborbs
logo: /assets/images/IMG_3198.jpg # path of site logo, e.g. "/assets/images/logo.png"
search: true # true, false (default)
search_full_content: true # true, false (default)
search_provider: # lunr (default), algolia

markdown: kramdown
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  
feed:
  path: atom.xml
