remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

lang: en-US
title: vaficionado.com
email:
description: where the cloud meets the vines
baseurl: /vaficionado # the optional subpath of your site, e.g. "/blog"
url: https://jonnyborbs.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
author:
  name: Jon
  twitter: jonnyborbs
  picture:  /assets/images/IMG_3198.jpg
twitter_username: jonnyborbs
github_username: jonnyborbs
logo: # path of site logo, e.g. "/vaficionado/assets/images/logo.png"
search: true # true, false (default)
search_full_content: false # true, false (default)
search_provider: # lunr (default), algolia
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false
